name: Release

on:
    push:
        branches: ["main"]

permissions:
    contents: write
    pull-requests: write
    id-token: write

jobs:
    pipes:
        uses: dragunovartem99/pipes/.github/workflows/release-npm.yaml@v2.0.0
